export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET'
export const GET_NUMBERS_BASKET = 'GET_NUMBERS_BASKET'
export const GET_SHOE_ITEMS = 'GET_SHOE_ITEMS'
export const ITEMS_LOADING = 'ITEMS_LOADING'

